config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
get 'home/about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
 <div class="container">
 <!-- Brand and toggle get grouped for better mobile display -->
 <div class="navbar-header">
 <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" datatarget="#bs-example-navbar-collapse-1">
 <span class="sr-only">Toggle navigation</span>
 <span class="icon-bar"></span>
 <span class="icon-bar"></span>
 <span class="icon-bar"></span>
 </button>
 <a class="navbar-brand" href="index">Reyna's Project</a>
 </div>
 <!-- Collect the nav links, forms, and other content for toggling -->
 <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
 <ul class="nav navbar-nav">
 <li><%= link_to 'Home', root_path %></li>
 <li><%= link_to 'About Me', home_about_path %></li>
 </ul>
 </div><!-- /.navbar-collapse -->
 </div><!-- /.container -->
 </nav>

app/views/home/about.html.erb
<h1>About Reyna!</h1>
<p>This is my life's work, I hope you enjoy it!</p>

app/views/home/index.html.erb
<div class="jumbotron">
 
<h1>Welcome to my Pinterested App!</h1>
<p>Pretty Cool, Don't You Think Clowns!</p>
<p>Please stay tuned as my new app develops.  It will be <strong>mind </strong>blowing!</p>
<%= link_to 'About Us', home_about_path, class: 'btn btn-primary' %>
<%= link_to 'Home', root_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'home/header' %>
<div class='container'>
  

<%= yield %>
</div>
</body>
</html>